# Generated by Django 5.1.5 on 2025-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
